### ISSUE TITLE
How to test rsocket without server 

### ISSUE THREAD

**Issue by nikitsenka** [trishagee/jb-stock-client#1]
Hi 
This is a great example. However the RSocketStockClientIntegrationTest can't be run without server. How can we mock the server?

**Comment by trishagee** [comment]
I haven't looked into stubbing or mocking anything, the integration test was specifically designed to require the server running because it tests the actual RSocket connection which was the bit that had a lot of uncertainty around it.

The way this small example stands, the server is little more than a stub anyway (it simply sends randomly generated prices) so there's little benefit in mocking the server. The whole example is about getting the "real" moving pieces working together. I don't think this example requires mocked or stubbed services, but I'd be happy to hear of tests or use cases that do need them.
